version: "3.8"
services:
  mongo:
    image: geppettotest/mongo-local:sept2021
    container_name: mongo-9318
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - healthmonkstart9941_9318-volume:/data/db
    ports:
      - "27018:27017"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u root -p root --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
  vault:
    image: vault:latest
    container_name: vault-9318
    ports:
      - "8200:8200"
    environment:
        VAULT_SERVER: "http://127.0.0.1:8200"
        VAULT_DEV_ROOT_TOKEN_ID: vault-geppetto-2021
    cap_add:
      - IPC_LOCK
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent


  authproxy:
    build: ../../../application/services/default_services/authproxy
    image: authproxy-9318
    container_name: authproxy-9318
    ports:
      - "0000:8001"
    env_file: .env
    depends_on:
      - mongo
      - gcam
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent

  securitymanager:
    build: ../../../application/services/default_services/securitymanager
    image: securitymanager-9318
    container_name: securitymanager-9318
    ports:
      - "8003:8003"
    env_file: .env
    depends_on:
      - mongo
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent

  systemcredentialmanager:
    build: ../../../application/services/default_services/systemcredentialmanager
    image: systemcredentialmanager-9318
    container_name: systemcredentialmanager-9318
    ports:
      - "8005:8005"
    env_file: .env
    depends_on:
      - mongo
      - vault
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent

  gepfilemanager:
    build: ../../../application/services/default_services/gepfilemanager
    image: gepfilemanager-9318
    container_name: gepfilemanager-9318
    ports:
      - "3015:3015"
    env_file: .env
    depends_on:
      - mongo
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent

  gcam:
    build: ../../../application/services/default_services/gcam
    image: gcam-9318
    container_name: gcam-9318
    ports:
      - "8007:8007"
    env_file: .env
    depends_on:
      - mongo
      - vault
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
     
     
  apigateway:
    build: ../../../application/services/custom_services/apigateway
    image: apigateway-9318
    container_name: apigateway-9318
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - authproxy
      - securitymanager
      - systemcredentialmanager
      - systementry
      - foodmanager
      - personmanager
      - nutrition
      - medicationmanager
      - prescriptionmanager
      - workout
      - sleeptrack

    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent

  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch-9318
    restart: always
    environment:
      - cluster.name=elasticsearch
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 262144
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    expose:
      - 9200
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer

  kibana:
    image: kibana:7.16.2
    container_name: kibana-9318
    restart: always
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

  fluentd:
    image: fluentd-9318
    build: ../../../application/services/default_services/fluentd/fluend
    volumes:
      - ../../../application/services/default_services/fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    restart: always
    container_name: fluentd-9318
    ports:
      - "24224:24224"
      - "24224:24224/udp"


  systementry: 
    build: ../../../application/services/custom_services/systementry
    image: systementry-9318
    container_name: systementry-9318
    ports: 
      - 8026:8026
    env_file: .env
    depends_on:
      - mongo
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent

  foodmanager: 
    build: ../../../application/services/custom_services/foodmanager
    image: foodmanager-9318
    container_name: foodmanager-9318
    ports: 
      - 8027:8027
    env_file: .env
    depends_on:
      - mongo
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent

  personmanager: 
    build: ../../../application/services/custom_services/personmanager
    image: personmanager-9318
    container_name: personmanager-9318
    ports: 
      - 8028:8028
    env_file: .env
    depends_on:
      - mongo
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent

  nutrition: 
    build: ../../../application/services/custom_services/nutrition
    image: nutrition-9318
    container_name: nutrition-9318
    ports: 
      - 8029:8029
    env_file: .env
    depends_on:
      - mongo
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent

  medicationmanager: 
    build: ../../../application/services/custom_services/medicationmanager
    image: medicationmanager-9318
    container_name: medicationmanager-9318
    ports: 
      - 8030:8030
    env_file: .env
    depends_on:
      - mongo
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent

  prescriptionmanager: 
    build: ../../../application/services/custom_services/prescriptionmanager
    image: prescriptionmanager-9318
    container_name: prescriptionmanager-9318
    ports: 
      - 8031:8031
    env_file: .env
    depends_on:
      - mongo
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent

  workout: 
    build: ../../../application/services/custom_services/workout
    image: workout-9318
    container_name: workout-9318
    ports: 
      - 8032:8032
    env_file: .env
    depends_on:
      - mongo
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent

  sleeptrack: 
    build: ../../../application/services/custom_services/sleeptrack
    image: sleeptrack-9318
    container_name: sleeptrack-9318
    ports: 
      - 8033:8033
    env_file: .env
    depends_on:
      - mongo
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent


volumes:
  healthmonkstart9941_9318-volume:
    driver: local
  elasticsearch:
